portto/wallet-web-ui

package.json, yarn.lock
Update to get the latest theme. Also, install `@chakra-ui/styled-system` to get typescript autocomplete working.
=> [Enhance] Install @chakra-ui/styled-system and upgrade @blocto/web-chakra-theme

.github/pr-labeler.yml, .github/pull_request_template.md, .github/workflows/pr-labeler.yml, README.md
- add pr labeler and pr template.
- add description of project structure to readme.
**Asana**:  - 
**Mockup**:   -
=> [Feat] Add pr labeler and pr template with some project description to readme.

src/apis/proxies/backend.ts, src/apis/wallet.ts, src/features/Authenticate/components/Input2FA.tsx, src/features/Authenticate/components/InputEmail.tsx, src/features/EVM/Signing/components/Connecting.tsx, src/features/EVM/Signing/components/NonCustodial.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/components/NonCustodial.tsx, src/services/Sentry/index.ts
- Throw the error caught from the request
- Update response types
- Fix getting the wrong value from the response
Detailed response types need to be implemented in the future when we need to get the other values from the response
**Asana**:  
**Mockup**:
=> [Enhance] Throw the error caught from the request

src/apis/proxies/backend.ts, src/apis/wallet.ts, src/components/Button.tsx, src/components/Layout.tsx, src/components/LinearSpinner.tsx, src/features/Authenticate/components/Input2FA.tsx, src/features/Authenticate/components/InputEmail.tsx, src/features/EVM/Signing/components/Connecting.tsx, src/features/EVM/Signing/components/NonCustodial.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/components/NonCustodial.tsx, src/mocks/index.ts, src/services/Sentry/index.ts, src/theme.ts
- Disallow to click the button again if it's already loading
- Remove hover style when the button is disabled
**Asana**:  
**Mockup**:
=> [Enhance] Prevent to click when the button it loading and update style

src/mocks/config.ts
Project cannot build successfully when we build it without actually putting `config.js` here
**Asana**:  
**Mockup**:
=> [Fix] Add the missing config for avoiding the build error

Dockerfile, cloudbuild.yaml, kubernetes/prod/deployment.yaml, kubernetes/prod/hpa.yaml, kubernetes/prod/ingress.yaml, kubernetes/prod/kustomization.yaml, kubernetes/prod/service.yaml
Deployment configs
**Asana**:  
**Mockup**:
=> Deployment

src/components/Field/index.tsx, src/features/EVM/Signing/components/Connecting.tsx, src/features/EVM/Signing/components/Main.tsx, src/features/EVM/Signing/components/NonCustodial.tsx, src/features/EVM/Signing/index.tsx
Update the UI for signing message on EVM
**Asana**:  
**Mockup**:  https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=309%3A12962&t=a202LCWbbPERLojb-1
=> Feature/evm sign UI

src/machines/authenticate/services.ts
Fix non-custodial users cannot login
**Asana**:  
**Mockup**:
=> [Fix] Login for non-custodial users

src/machines/authenticate/definition.ts
=> [Hoftix] Authentication machine

src/features/EVM/Transaction/components/NonCustodial.tsx, src/features/EVM/Transaction/index.tsx
Add non-custodial ui for evm transaction.
**Asana**:  https://app.asana.com/0/0/1203528095106279/f
**Mockup**:
=> Add non-custodial ui for evm transaction.

package.json, src/App.tsx, src/apis/wallet.ts, src/components/TransactionInfo.tsx, src/features/EVM/Signing/components/Connecting.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/messages.js, src/features/EVM/Transaction/hooks/useTransactionDetail.tsx, src/features/Flow/Transaction/components/Connecting.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Flow/Transaction/hooks/useTransactionDetail.ts, src/features/Flow/Transaction/index.tsx, src/services/Env/index.ts, src/services/Flow/getFlowScriptWithTemplate.ts, src/services/Flow/index.ts, src/services/Flow/recognizeTx.ts, src/types.ts, src/utils/hasMsg.tsx, src/utils/hashMsg.tsx, yarn.lock
- add flow transaction view.
- copy some flow util function like `hashMsg` and `recognizeTx` from old wallet-webapp.
**Asana**:  https://app.asana.com/0/0/1203528095106279/f
**Mockup**:
=> [Feat] Add transaction view for flow.

src/features/Flow/Transaction/index.tsx, src/services/Env/index.ts, src/services/Flow/recognizeTx.ts
- Fix the layout logic in flow chain, and env logic error.
**Asana**:  -
**Mockup**:  -
I changes: You can provide a before-and-after screenshot with highlighting the changes or a link to a video/GIF. -->
=> Fix the layout logic in flow chain, and env logic error.

src/services/Amplitude/log.ts, src/services/Env/index.ts, src/services/Frame/utils.ts, src/services/Sentry/index.ts, src/theme.ts
=> [Fix] Wrong env variable for REACT_APP_ENV

src/features/Aptos/Transaction/components/Connecting.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/Aptos/Transaction/components/NonCustodial.tsx, src/features/Aptos/Transaction/index.tsx, src/features/EVM/Signing/components/NonCustodial.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/NonCustodial.tsx, src/features/EVM/Transaction/index.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Flow/Transaction/components/NonCustodial.tsx, src/features/Flow/Transaction/index.tsx, src/features/Solana/Transaction/components/Connecting.tsx, src/features/Solana/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/NonCustodial.tsx, src/features/Solana/Transaction/index.tsx, src/hooks/useNonCustodialTransaction.tsx, src/machines/transaction/definition.ts
- Add non-custodial view for flow / solana / aptos.
- drag the creating signing request flow when sending tx out to be a separated hook. 
**Asana**:  https://app.asana.com/0/1201812548509877/1203488492251068/f
**Mockup**:  https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=129:18156&t=IjlGuZ1Rwsng6EoA-0
=> Add non-custodial view for flow / solana / aptos.

src/features/Flow/Transaction/components/DangerousTxAlert.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Flow/Transaction/index.tsx, src/machines/transaction/definition.ts, src/messages/defaultMessages.json, src/types.ts, src/utils/isMaliciousTx.ts
=> Add malicious tx alert ui.

.eslintrc.json, src/apis/wallet.ts, src/features/Authenticate/components/Connecting.tsx, src/features/Authenticate/components/InputEmail.tsx, src/features/Authenticate/components/Queueing.tsx, src/features/Authenticate/index.tsx, src/machines/authenticate/definition.ts
Skip entering the email if there's prefilled email in the URL
Following the spec here: https://docs.blocto.app/blocto-sdk/javascript-sdk/flow/login-register#step-1-configure-fcl
**Asana**:  
**Mockup**:
=> [Feature] Forward to the page entering OTP code if there's prefilled email

src/apis/wallet.ts, src/components/TransactionInfo.tsx, src/features/Aptos/Transaction/components/Connecting.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/Flow/Transaction/components/Connecting.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/Connecting.tsx, src/features/Solana/Transaction/components/Main.tsx, src/machines/transaction/definition.ts, src/machines/transaction/services.ts
Add the missing part of updating authorization information.
**Asana**:  https://app.asana.com/0/1201812548509877/1203488492251068/f
**Mockup**:
=> Update authorization detail before closing the frame.

src/features/Aptos/Signing/components/Connecting.tsx, src/features/Aptos/Signing/index.tsx, src/features/Aptos/Transaction/components/Connecting.tsx, src/features/Aptos/Transaction/index.tsx, src/features/Authenticate/components/Connecting.tsx, src/features/EVM/Signing/components/Connecting.tsx, src/features/EVM/Signing/index.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/index.tsx, src/features/Flow/Signing/components/Connecting.tsx, src/features/Flow/Signing/index.tsx, src/features/Flow/Transaction/components/Connecting.tsx, src/features/Flow/Transaction/index.tsx, src/features/Solana/Transaction/components/Connecting.tsx, src/features/Solana/Transaction/index.tsx
If the app id is not provided, we need to get the dApp's url from the browser as we discussed in the syc-up meeting
**Asana**:  
**Mockup**:
=> [Refactor] Still need to get the url from the browser if the app id does not present

src/features/Authenticate/components/AccountConfirm.tsx, src/features/Authenticate/components/RunInitScripts.tsx, src/features/Authenticate/index.tsx, src/machines/authenticate/definition.ts
Remove the RUN_INIT_SCRIPTS state or it'll show a weird UI for non-custodial users after logging in
https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=509%3A13682&t=Cbhs4xJDlb5kdBJe-1
Should implement this UI in v2.1.0
**Asana**:  
**Mockup**:
=> [Enhance] Remove machineStates.RUN_INIT_SCRIPTS

src/features/Authenticate/index.tsx
Store authenticationId in xstate machine :P
**Asana**:  
**Mockup**:
=> [Fix] Store authenticationId

src/features/Authenticate/components/InputEmail.tsx
Press enter key to submit email
**Asana**:  
**Mockup**:
=> [Feature] Press enter to submit email

src/index.tsx
Fix Buffer is not defined
**Asana**:  
**Mockup**:
=> [Fix] Manage to expose Buffer

src/features/EVM/Signing/components/Connecting.tsx, src/features/Flow/Signing/components/Connecting.tsx
Show the real message instead of the hex data
**Asana**:  
**Mockup**:
=> [Fix] Fix the message shown on the UI for the signing message on EVM

src/machines/authenticate/definition.ts, src/machines/authenticate/services.ts
Fix authenticationId
**Asana**:  
**Mockup**:
=> [Fix] Getting authenticationId from the wrong place

src/features/Aptos/Transaction/hooks/useTransactionDetail.tsx, src/features/Authenticate/components/Input2FA.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/EVM/Transaction/hooks/useTransactionDetail.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Flow/Transaction/hooks/useTransactionDetail.ts, src/features/Solana/Transaction/components/Main.tsx, src/features/Solana/Transaction/index.tsx, src/machines/transaction/definition.ts, src/messages/index.ts, src/services/Amplitude/log.ts, src/services/Flow/recognizeTx.ts, src/services/Frame/eventHandlers.ts, src/services/Frame/utils.ts, src/services/GoogleAnalytics/index.ts, src/services/Sentry/index.ts, src/types.ts
=> [Refactor] Fix some eslint warnings

cli/dev-tool
=> [Enhance] Slightly adjust cli dev-tool

src/features/Aptos/Transaction/components/Main.tsx
- Set tx as verified if tx type is entry_function_payload
**Asana**:  https://app.asana.com/0/0/1204019489297762/f
**Mockup**:
=> [Fix] Set tx as verified if tx type is entry_function_payload

src/apis/axios.ts, src/machines/authenticate/services.ts, src/services/LocalStorage/constants.ts
Pass app id in the header to make sure wallet-web-backend recognizes the current app
**Asana**:  https://app.asana.com/0/0/1204029950756246/f
**Mockup**:
=> [Fix] Include app id in the request header

src/components/Header/index.tsx, src/components/Loading.tsx, src/features/Aptos/Signing/components/NonCustodial.tsx, src/features/Aptos/Transaction/components/NonCustodial.tsx, src/features/Authenticate/components/Queueing.tsx, src/features/EVM/Signing/components/NonCustodial.tsx, src/features/EVM/Transaction/components/NonCustodial.tsx, src/features/Flow/NonCustodial/index.tsx, src/features/Flow/PreAuthz/index.tsx, src/features/Flow/Transaction/components/DangerousTxAlert.tsx, src/features/Flow/Transaction/index.tsx, src/features/Solana/Transaction/components/NonCustodial.tsx, src/messages/defaultMessages.json, src/theme.ts
- Update dangerous alert UI that raised by designer.
**Asana**: https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=1553%3A15788&t=aUfa5gLNP9v2ad9X-1
**Mockup**:
=> [Feat] Update dangerousAlert UI.

src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
- fix unit error with user's balance.
**Asana**:  https://app.asana.com/0/0/1204019489297778/f
**Mockup**:
=> [Fix] Fix transfer unit to eth with user's native token balance.

src/features/Authenticate/components/InputEmail.tsx, src/features/EVM/Transaction/hooks/useTransactionDetail.tsx
- fix logic bugs.
**Asana**:  
- https://app.asana.com/0/0/1204019489297771/f
- https://app.asana.com/0/1201812548509877/1204086912729821/f
**Mockup**:
=> Fix ui at login and tx logic bugs on evm.

src/components/Header/index.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/Main.tsx
- add loading state on approve button in every tx view.
- fix visibility for the network label in the Header component.
**Asana**:  https://app.asana.com/0/0/1204019489297757/f
**Mockup**:  -
=> [Feat] loading state for approve button in tx view.

src/features/Aptos/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/Main.tsx
- disable approve button when estimating point.
- add another state for disabling the button.
- these logic will be refactor with this [PR](https://github.com/portto/wallet-web-ui/pull/69) later ,it's just for qa purpose.
**Asana**:  https://app.asana.com/0/0/1204019489297757/f
**Mockup**:
=> [Feat] disable approve button when estimating point.

src/features/Aptos/Transaction/hooks/useTransactionDetail.tsx, src/features/Flow/Transaction/hooks/useTransactionDetail.ts
- Fix unit problem for user's balance on aptos and flow.
**Asana**:  
**Mockup**:
=> Fix unit problem for user's balance on aptos and flow.

src/apis/wallet.ts, src/components/TransactionFeeField.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/Main.tsx, src/hooks/useEstimatePointInterval.ts, src/hooks/useEstimatePointInteval.ts, src/hooks/useInterval.ts
- make estimate point logic into a separate component.
- add interval for updating tx fee by polling.
**Asana**:  - 
**Mockup**:  -
=> [Refactor]  Estimate tx fee logic and ui component.

src/components/transaction/TransactionSent.tsx, src/messages/defaultMessages.json
Update translation strings
**Asana**:  
**Mockup**:  
- https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD?node-id=1850:17237#382713513
- https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD?node-id=1850:17237#382581671
=> [Enhance] Update translation strings for the onboarding page

src/services/Frame/eventHandlers.ts
Should pass session id
**Asana**:  
**Mockup**:
=> [Fix] Should pass session id instead of auth token

src/machines/authenticate/services.ts
**Asana**:  
**Mockup**:  
The previous version utilized the URL host as a condition:
https://github.com/portto/wallet-webapp/blob/7a0c1c3b4802b4656cff4398e89366feeb18d838/app/containers/Authn/index.js#L908-L925
However, the current version sets the URL in the state context using ```const url = search.get("l6n");``` and employs this URL here:
https://github.com/portto/wallet-web-ui/blob/d2b37d6594152659cf30f3feab67e1c39892bda5/src/features/Authenticate/index.tsx#L74
https://github.com/portto/wallet-web-ui/blob/d2b37d6594152659cf30f3feab67e1c39892bda5/src/machines/authenticate/services.ts#L134
=> [Fix] Identify exceptions

src/components/ActivityDetail.tsx, src/components/ScrollableContainer.tsx, src/components/ScrollableSection.tsx, src/components/transaction/TransactionFeeField.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/Flow/Transaction/components/Main.tsx, src/features/Solana/Transaction/components/Main.tsx, src/messages/defaultMessages.json
- Add activity detail field on tx view.
**Asana**:  
**Mockup**:  https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=1105%3A15190&t=NYxRTePu5Lpn9cc1-1
=> [Feat] add activity detail field.

src/components/transaction/TransactionFeeField.tsx
**Slack**: https://portto.slack.com/archives/C04FTRK0M3J/p1678348099788109?thread_ts=1678343140.159609&cid=C04FTRK0M3J
**Asana**:  
**Mockup**:
=> [Fix] Displaying the image with a wrong way

kubernetes/dev/ingress.yaml, kubernetes/prod/ingress.yaml, kubernetes/staging/ingress.yaml
**Asana**:  https://app.asana.com/0/1201812548509877/1203853750740177/f
**Mockup**:
=> [Fix] rename path

src/apis/proxies/backend.ts
- change endpoint for using proxy on dapps relared api. 
**Asana**:  https://app.asana.com/0/1201812548509877/1203853749872835/f
**Mockup**:  
- https://github.com/portto/wallet-web-backend/pull/25
=> [Feat] change endpoint for using proxy on dapps relared api.

kubernetes/dev/ingress.yaml, kubernetes/prod/ingress.yaml, kubernetes/staging/ingress.yaml, src/apis/proxies/backend.ts
- change endpoint for using proxy on dapps relared api. 
**Asana**:  https://app.asana.com/0/1201812548509877/1203853749872835/f
**Mockup**:  
- https://github.com/portto/wallet-web-backend/pull/25
=> [Feat] change endpoint for using proxy on dapps relared api. 

src/apis/wallet.ts, src/features/Aptos/Transaction/components/Connecting.tsx, src/types.ts
Get the requestId from the response for authz actions on Aptos
**Asana**:  https://app.asana.com/0/1201812548509877/1204004296893665/f
**Mockup**:  
https://github.com/portto/wallet-web-backend/pull/30
=> [Refactor] Get the requestId from the response

src/components/transaction/FeeOptions.tsx, src/components/transaction/TransactionFeeField.tsx, src/features/Aptos/Transaction/components/Connecting.tsx, src/features/Aptos/Transaction/components/Main.tsx, src/features/Aptos/Transaction/index.tsx, src/features/EVM/Transaction/components/Connecting.tsx, src/features/EVM/Transaction/components/Main.tsx, src/features/EVM/Transaction/index.tsx, src/features/Flow/Transaction/components/Connecting.tsx, src/features/Flow/Transaction/index.tsx, src/features/Solana/Transaction/components/Connecting.tsx, src/features/Solana/Transaction/components/Main.tsx, src/features/Solana/Transaction/index.tsx, src/types.ts
-  disable approve button when user has insufficient point.
-  and fix the logic of showing loading state on estimate point field.
**Asana**:  
**Mockup**:  https://www.figma.com/file/X8Jx6GxcEB9gxoMxujdDSD/7.-Wallet-Web-2.0?node-id=1850%3A17173&t=pEJ97THcuSAFXyEQ-1
=> Fix: disable approve button when user has insufficient point.

src/services/Amplitude/log.ts, src/utils/normalizeDomain.ts
=> [Feature] Normalize domain param
